// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'cross': string;
  'current': string;
  'dark': string;
  'deleteButton': string;
  'important': string;
  'row': string;
  'taskData': string;
  'type': string;
  'urgent': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
