export const BAD_REQUEST_400 = 'Неправильный логин или пароль'
export const NOT_AUTHORIZED_401 = 'Неправильный логин или пароль'
export const FORBIDDEN_403 = 'Недостаточно прав доступа'
export const NOT_FOUND_404 = 'Данные не найдены'
export const SERVER_ERROR_500 = 'Ошибка сервераю Попробуйте позже'

export const TASK_CREATED = 'Задача успешно добавлена'
export const TASK_NOT_CREATED = 'Задача не добавлена'
export const TASK_UPDATED = 'Задача успешно обновлена'
export const TASK_NOT_UPDATED = 'Задача не обновлена'
export const TASK_DELETED = 'Задача успешно удалена'
export const TASK_NOT_DELETED = 'Задача не удалена'