// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttons': string;
  'cancel': string;
  'error': string;
  'fieldset': string;
  'form': string;
  'input': string;
  'inputWrapper': string;
  'label': string;
  'legend': string;
  'select': string;
  'textarea': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
