// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addTask': string;
  'arrow': string;
  'button': string;
  'today': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
