// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current': string;
  'important': string;
  'urgent': string;
}
export const cssExports: CssExports;
export default cssExports;
