// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cell': string;
  'column': string;
  'currentDate': string;
  'tasks': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
