// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'context': string;
  'modal': string;
}
export const cssExports: CssExports;
export default cssExports;
