// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'fieldset': string;
  'form': string;
  'input': string;
  'inputWrapper': string;
  'label': string;
  'legend': string;
  'submitButton': string;
}
export const cssExports: CssExports;
export default cssExports;
